-- Competitive Velocity Analysis Dashboard
-- Generated by Systematic L1→L4 Intelligence Framework
-- Run ID: warby_parker_20250918_145751


        -- Competitive Velocity Analysis Dashboard (Phase 2)
        -- Measures acceleration and deceleration across all intelligence dimensions

        WITH weekly_intelligence_metrics AS (
          SELECT
            brand,
            DATE_TRUNC(DATE(start_timestamp), WEEK(MONDAY)) as week_start,

            -- Creative Velocity Metrics
            COUNT(*) as weekly_ads,
            AVG(LENGTH(COALESCE(creative_text, ''))) as avg_creative_length,
            COUNT(DISTINCT REGEXP_EXTRACT(creative_text, r'\b(\w+)\b')) as unique_creative_words,

            -- Channel Momentum Metrics
            COUNT(DISTINCT media_type) as channel_diversity,
            AVG(ARRAY_LENGTH(platforms_array)) as avg_platform_reach,
            SUM(CASE WHEN media_type = 'VIDEO' THEN 1 ELSE 0 END) as video_ads,

            -- Visual Evolution Metrics
            AVG(CASE WHEN LENGTH(creative_text) > 100 THEN 1.0 ELSE 0.0 END) as long_form_rate,
            AVG(duration_quality_weight) as avg_quality_score

          FROM `bigquery-ai-kaggle-469620.ads_demo.ads_with_dates`
          WHERE creative_text IS NOT NULL
            AND start_timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 16 WEEK)
          GROUP BY brand, week_start
        ),

        velocity_calculations AS (
          SELECT
            brand,
            week_start,
            weekly_ads,
            avg_creative_length,
            unique_creative_words,
            channel_diversity,
            avg_platform_reach,
            video_ads,
            long_form_rate,
            avg_quality_score,

            -- Creative Velocity: Rate of change in creative output
            (weekly_ads - LAG(weekly_ads, 1) OVER (PARTITION BY brand ORDER BY week_start)) as creative_volume_velocity_1w,
            (weekly_ads - LAG(weekly_ads, 4) OVER (PARTITION BY brand ORDER BY week_start)) / 4.0 as creative_volume_velocity_4w,

            -- Creative Sophistication Velocity
            (avg_creative_length - LAG(avg_creative_length, 1) OVER (PARTITION BY brand ORDER BY week_start)) as creative_length_velocity_1w,
            (unique_creative_words - LAG(unique_creative_words, 1) OVER (PARTITION BY brand ORDER BY week_start)) as creative_diversity_velocity_1w,

            -- Channel Momentum: Rate of platform expansion
            (avg_platform_reach - LAG(avg_platform_reach, 1) OVER (PARTITION BY brand ORDER BY week_start)) as platform_momentum_1w,
            (channel_diversity - LAG(channel_diversity, 1) OVER (PARTITION BY brand ORDER BY week_start)) as channel_expansion_velocity_1w,

            -- Visual Evolution Speed
            (video_ads - LAG(video_ads, 1) OVER (PARTITION BY brand ORDER BY week_start)) as video_adoption_velocity_1w,
            (long_form_rate - LAG(long_form_rate, 1) OVER (PARTITION BY brand ORDER BY week_start)) as content_sophistication_velocity_1w

          FROM weekly_intelligence_metrics
        ),

        competitive_velocity_ranking AS (
          SELECT
            *,

            -- Current week competitive velocity rankings
            RANK() OVER (PARTITION BY week_start ORDER BY ABS(COALESCE(creative_volume_velocity_1w, 0)) DESC) as creative_velocity_rank,
            RANK() OVER (PARTITION BY week_start ORDER BY ABS(COALESCE(platform_momentum_1w, 0)) DESC) as platform_momentum_rank,
            RANK() OVER (PARTITION BY week_start ORDER BY ABS(COALESCE(channel_expansion_velocity_1w, 0)) DESC) as channel_velocity_rank,
            RANK() OVER (PARTITION BY week_start ORDER BY ABS(COALESCE(video_adoption_velocity_1w, 0)) DESC) as visual_velocity_rank,

            -- Velocity classification
            CASE
              WHEN COALESCE(creative_volume_velocity_1w, 0) >= 5 THEN 'ACCELERATING_FAST'
              WHEN COALESCE(creative_volume_velocity_1w, 0) >= 2 THEN 'ACCELERATING'
              WHEN COALESCE(creative_volume_velocity_1w, 0) <= -5 THEN 'DECELERATING_FAST'
              WHEN COALESCE(creative_volume_velocity_1w, 0) <= -2 THEN 'DECELERATING'
              ELSE 'STABLE_VELOCITY'
            END as creative_velocity_classification,

            CASE
              WHEN COALESCE(platform_momentum_1w, 0) >= 1.0 THEN 'EXPANDING_FAST'
              WHEN COALESCE(platform_momentum_1w, 0) >= 0.5 THEN 'EXPANDING'
              WHEN COALESCE(platform_momentum_1w, 0) <= -1.0 THEN 'CONTRACTING_FAST'
              WHEN COALESCE(platform_momentum_1w, 0) <= -0.5 THEN 'CONTRACTING'
              ELSE 'STABLE_REACH'
            END as platform_momentum_classification

          FROM velocity_calculations
        ),

        velocity_summary AS (
          SELECT
            brand,
            week_start,

            -- Current metrics
            weekly_ads,
            ROUND(avg_creative_length, 1) as avg_creative_length,
            unique_creative_words,
            channel_diversity,
            ROUND(avg_platform_reach, 1) as avg_platform_reach,
            video_ads,
            ROUND(long_form_rate * 100, 1) as long_form_pct,
            ROUND(avg_quality_score, 3) as avg_quality_score,

            -- Velocity metrics (1-week)
            ROUND(COALESCE(creative_volume_velocity_1w, 0), 1) as creative_volume_velocity_1w,
            ROUND(COALESCE(creative_length_velocity_1w, 0), 1) as creative_length_velocity_1w,
            ROUND(COALESCE(creative_diversity_velocity_1w, 0), 1) as creative_diversity_velocity_1w,
            ROUND(COALESCE(platform_momentum_1w, 0), 2) as platform_momentum_1w,
            ROUND(COALESCE(channel_expansion_velocity_1w, 0), 1) as channel_expansion_velocity_1w,
            ROUND(COALESCE(video_adoption_velocity_1w, 0), 1) as video_adoption_velocity_1w,
            ROUND(COALESCE(content_sophistication_velocity_1w, 0), 3) as content_sophistication_velocity_1w,

            -- Velocity metrics (4-week trend)
            ROUND(COALESCE(creative_volume_velocity_4w, 0), 2) as creative_volume_velocity_4w,

            -- Competitive rankings
            creative_velocity_rank,
            platform_momentum_rank,
            channel_velocity_rank,
            visual_velocity_rank,

            -- Classifications
            creative_velocity_classification,
            platform_momentum_classification,

            -- Overall velocity score (composite of all dimensions)
            ROUND((
              ABS(COALESCE(creative_volume_velocity_1w, 0)) * 0.3 +
              ABS(COALESCE(platform_momentum_1w, 0)) * 10 * 0.3 +  -- Scale platform momentum
              ABS(COALESCE(channel_expansion_velocity_1w, 0)) * 0.2 +
              ABS(COALESCE(video_adoption_velocity_1w, 0)) * 0.2
            ), 2) as overall_velocity_score,

            -- Strategic velocity insight
            CASE
              WHEN creative_velocity_rank <= 2 AND platform_momentum_rank <= 2 THEN 'MULTI_DIMENSIONAL_LEADER'
              WHEN creative_velocity_rank <= 2 THEN 'CREATIVE_VELOCITY_LEADER'
              WHEN platform_momentum_rank <= 2 THEN 'PLATFORM_MOMENTUM_LEADER'
              WHEN channel_velocity_rank <= 2 THEN 'CHANNEL_EXPANSION_LEADER'
              WHEN visual_velocity_rank <= 2 THEN 'VISUAL_EVOLUTION_LEADER'
              ELSE 'STABLE_STRATEGIC_POSITION'
            END as velocity_leadership_type

          FROM competitive_velocity_ranking
        )

        SELECT *
        FROM velocity_summary
        WHERE week_start >= DATE_SUB(CURRENT_DATE(), INTERVAL 12 WEEK)  -- Last 12 weeks
        ORDER BY week_start DESC, overall_velocity_score DESC
        