-- Competitive Intelligence Analysis Dashboard
-- Generated by Systematic L1→L4 Intelligence Framework
-- Run ID: warby_parker_20250917_163215


            -- General Intelligence Dashboard
            WITH general_metrics AS (
              SELECT
                brand,
                COUNT(*) as total_signals,
                COUNT(DISTINCT DATE(start_timestamp)) as active_days,
                MIN(start_timestamp) as first_seen,
                MAX(start_timestamp) as last_seen,
                AVG(LENGTH(COALESCE(creative_text, ''))) as avg_content_length,
                COUNT(DISTINCT publisher_platforms) as platform_count
              FROM `bigquery-ai-kaggle-469620.ads_demo.ads_with_dates`
              GROUP BY brand
            )
            SELECT
              brand,
              total_signals,
              active_days,
              first_seen,
              last_seen,
              ROUND(avg_content_length, 1) as avg_content_length,
              platform_count,
              ROUND(total_signals / GREATEST(active_days, 1), 2) as signals_per_day
            FROM general_metrics
            ORDER BY total_signals DESC
            