-- Visual Style Competitive Matrix Dashboard
-- Generated by Systematic L1→L4 Intelligence Framework
-- Run ID: warby_parker_20250921_000647


        -- Visual Style Competitive Matrix
        -- Enhanced Visual Intelligence Dashboard for Style Analysis
        WITH style_matrix AS (
          SELECT
            brand,
            COUNT(*) as total_ads,
            COUNTIF(visual_style = 'MINIMALIST') * 100.0 / COUNT(*) as minimalist_pct,
            COUNTIF(visual_style = 'LUXURY') * 100.0 / COUNT(*) as luxury_pct,
            COUNTIF(visual_style = 'BOLD') * 100.0 / COUNT(*) as bold_pct,
            COUNTIF(visual_style = 'CASUAL') * 100.0 / COUNT(*) as casual_pct,
            COUNTIF(visual_style = 'PROFESSIONAL') * 100.0 / COUNT(*) as professional_pct,
            AVG(brand_consistency_score) as avg_brand_consistency,
            AVG(luxury_positioning_score) as avg_luxury_score,
            AVG(boldness_score) as avg_boldness_score
          FROM `bigquery-ai-kaggle-469620.ads_demo.ads_with_dates`
          WHERE visual_style IS NOT NULL
          GROUP BY brand
        ),
        competitive_gaps AS (
          SELECT
            'MINIMALIST' as style,
            AVG(minimalist_pct) as market_avg,
            MAX(minimalist_pct) - MIN(minimalist_pct) as market_spread,
            STDDEV(minimalist_pct) as market_volatility
          FROM style_matrix
          UNION ALL
          SELECT
            'LUXURY' as style,
            AVG(luxury_pct) as market_avg,
            MAX(luxury_pct) - MIN(luxury_pct) as market_spread,
            STDDEV(luxury_pct) as market_volatility
          FROM style_matrix
          UNION ALL
          SELECT
            'BOLD' as style,
            AVG(bold_pct) as market_avg,
            MAX(bold_pct) - MIN(bold_pct) as market_spread,
            STDDEV(bold_pct) as market_volatility
          FROM style_matrix
          UNION ALL
          SELECT
            'CASUAL' as style,
            AVG(casual_pct) as market_avg,
            MAX(casual_pct) - MIN(casual_pct) as market_spread,
            STDDEV(casual_pct) as market_volatility
          FROM style_matrix
          UNION ALL
          SELECT
            'PROFESSIONAL' as style,
            AVG(professional_pct) as market_avg,
            MAX(professional_pct) - MIN(professional_pct) as market_spread,
            STDDEV(professional_pct) as market_volatility
          FROM style_matrix
        ),
        competitive_advantage AS (
          SELECT
            sm.brand,
            sm.total_ads,
            ROUND(sm.minimalist_pct, 1) as minimalist_pct,
            ROUND(sm.luxury_pct, 1) as luxury_pct,
            ROUND(sm.bold_pct, 1) as bold_pct,
            ROUND(sm.casual_pct, 1) as casual_pct,
            ROUND(sm.professional_pct, 1) as professional_pct,
            ROUND(sm.avg_brand_consistency, 3) as brand_consistency_score,
            ROUND(sm.avg_luxury_score, 3) as luxury_positioning_score,
            ROUND(sm.avg_boldness_score, 3) as boldness_score,
            -- Competitive advantage indicators
            CASE
              WHEN sm.minimalist_pct > (SELECT market_avg FROM competitive_gaps WHERE style = 'MINIMALIST') + 20 THEN 'DOMINATES_MINIMALIST'
              WHEN sm.luxury_pct > (SELECT market_avg FROM competitive_gaps WHERE style = 'LUXURY') + 20 THEN 'DOMINATES_LUXURY'
              WHEN sm.bold_pct > (SELECT market_avg FROM competitive_gaps WHERE style = 'BOLD') + 20 THEN 'DOMINATES_BOLD'
              WHEN sm.casual_pct > (SELECT market_avg FROM competitive_gaps WHERE style = 'CASUAL') + 20 THEN 'DOMINATES_CASUAL'
              WHEN sm.professional_pct > (SELECT market_avg FROM competitive_gaps WHERE style = 'PROFESSIONAL') + 20 THEN 'DOMINATES_PROFESSIONAL'
              ELSE 'BALANCED_PORTFOLIO'
            END as style_advantage,
            -- Style diversification score (lower = more focused, higher = more diverse)
            (sm.minimalist_pct * sm.minimalist_pct + sm.luxury_pct * sm.luxury_pct +
             sm.bold_pct * sm.bold_pct + sm.casual_pct * sm.casual_pct +
             sm.professional_pct * sm.professional_pct) / 10000.0 as style_concentration_index
          FROM style_matrix sm
        )
        SELECT
          brand,
          total_ads,
          minimalist_pct,
          luxury_pct,
          bold_pct,
          casual_pct,
          professional_pct,
          brand_consistency_score,
          luxury_positioning_score,
          boldness_score,
          style_advantage,
          ROUND(style_concentration_index, 3) as style_focus_score,
          CASE
            WHEN style_concentration_index > 0.4 THEN 'HIGHLY_FOCUSED'
            WHEN style_concentration_index > 0.25 THEN 'MODERATELY_FOCUSED'
            ELSE 'DIVERSIFIED'
          END as style_strategy
        FROM competitive_advantage
        ORDER BY total_ads DESC
        