-- Visual Intelligence Analysis Dashboard
-- Generated by Systematic L1→L4 Intelligence Framework
-- Run ID: warby_parker_20250917_105909


            -- Visual Intelligence Dashboard
            WITH visual_metrics AS (
              SELECT
                brand,
                COUNT(*) as total_visual_ads,
                AVG(visual_text_alignment_score) as avg_visual_alignment,
                AVG(brand_consistency_score) as avg_brand_consistency,
                AVG(luxury_positioning_score) as avg_luxury_position,
                AVG(boldness_score) as avg_boldness,
                AVG(visual_differentiation_level) as avg_differentiation,
                AVG(creative_pattern_risk) as avg_pattern_risk,
                STRING_AGG(DISTINCT target_demographic, ', ') as target_demographics,
                -- Positioning quadrant classification
                CASE
                  WHEN AVG(luxury_positioning_score) > 0.7 AND AVG(boldness_score) > 0.7 THEN 'Luxury-Bold'
                  WHEN AVG(luxury_positioning_score) > 0.7 AND AVG(boldness_score) < 0.4 THEN 'Luxury-Subtle'
                  WHEN AVG(luxury_positioning_score) < 0.4 AND AVG(boldness_score) > 0.7 THEN 'Accessible-Bold'
                  ELSE 'Mid-Balanced'
                END as positioning_quadrant,
                -- Visual health score
                (AVG(visual_text_alignment_score) * 0.3 +
                 AVG(brand_consistency_score) * 0.3 +
                 AVG(visual_differentiation_level) * 0.2 +
                 (1 - AVG(creative_pattern_risk)) * 0.2) as visual_health_score
              FROM (
                SELECT * FROM `bigquery-ai-kaggle-469620.ads_demo.visual_intelligence_*`
                WHERE luxury_positioning_score IS NOT NULL
              )
              GROUP BY brand
            )
            SELECT
              brand,
              total_visual_ads,
              ROUND(avg_visual_alignment, 3) as visual_alignment_score,
              ROUND(avg_brand_consistency, 3) as brand_consistency_score,
              ROUND(avg_luxury_position, 3) as luxury_positioning,
              ROUND(avg_boldness, 3) as boldness_score,
              ROUND(avg_differentiation, 3) as differentiation_level,
              ROUND(avg_pattern_risk, 3) as fatigue_risk,
              target_demographics,
              positioning_quadrant,
              ROUND(visual_health_score, 3) as overall_visual_health
            FROM visual_metrics
            ORDER BY total_visual_ads DESC
            