-- Visual Intelligence Analysis Dashboard
-- Generated by Systematic L1→L4 Intelligence Framework
-- Run ID: warby_parker_20250918_144858


            -- Visual Intelligence Dashboard with Temporal Analysis (Phase 1)
            WITH weekly_visual_metrics AS (
              SELECT
                brand,
                DATE_TRUNC(DATE(start_timestamp), WEEK(MONDAY)) as week_start,
                COUNT(*) as weekly_visual_ads,
                AVG(visual_text_alignment_score) as avg_visual_alignment,
                AVG(brand_consistency_score) as avg_brand_consistency,
                AVG(luxury_positioning_score) as avg_luxury_position,
                AVG(boldness_score) as avg_boldness,
                AVG(visual_differentiation_level) as avg_differentiation,
                AVG(creative_pattern_risk) as avg_pattern_risk,
                -- Visual health score per week
                (AVG(visual_text_alignment_score) * 0.3 +
                 AVG(brand_consistency_score) * 0.3 +
                 AVG(visual_differentiation_level) * 0.2 +
                 (1 - AVG(creative_pattern_risk)) * 0.2) as weekly_visual_health_score
              FROM (
                SELECT * FROM `bigquery-ai-kaggle-469620.ads_demo.visual_intelligence_*`
                WHERE luxury_positioning_score IS NOT NULL
                  AND start_timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 12 WEEK)
              )
              GROUP BY brand, week_start
            ),
            temporal_analysis AS (
              SELECT
                brand, week_start, weekly_visual_ads, avg_visual_alignment, avg_brand_consistency,
                avg_luxury_position, avg_boldness, avg_differentiation, avg_pattern_risk, weekly_visual_health_score,
                -- Week-over-week changes
                LAG(weekly_visual_ads) OVER (PARTITION BY brand ORDER BY week_start) as prev_week_ads,
                LAG(avg_luxury_position) OVER (PARTITION BY brand ORDER BY week_start) as prev_luxury_position,
                LAG(avg_boldness) OVER (PARTITION BY brand ORDER BY week_start) as prev_boldness,
                LAG(avg_brand_consistency) OVER (PARTITION BY brand ORDER BY week_start) as prev_brand_consistency,
                LAG(avg_pattern_risk) OVER (PARTITION BY brand ORDER BY week_start) as prev_pattern_risk,
                -- Competitive ranking
                RANK() OVER (PARTITION BY week_start ORDER BY weekly_visual_ads DESC) as weekly_volume_rank,
                RANK() OVER (PARTITION BY week_start ORDER BY avg_luxury_position DESC) as weekly_luxury_rank,
                RANK() OVER (PARTITION BY week_start ORDER BY avg_boldness DESC) as weekly_boldness_rank,
                RANK() OVER (PARTITION BY week_start ORDER BY weekly_visual_health_score DESC) as weekly_health_rank
              FROM weekly_visual_metrics
            ),
            visual_summary AS (
              SELECT
                brand,
                COUNT(*) as weeks_active,
                SUM(weekly_visual_ads) as total_visual_ads,
                AVG(avg_visual_alignment) as overall_visual_alignment,
                AVG(avg_brand_consistency) as overall_brand_consistency,
                AVG(avg_luxury_position) as overall_luxury_position,
                AVG(avg_boldness) as overall_boldness,
                AVG(avg_differentiation) as overall_differentiation,
                AVG(avg_pattern_risk) as overall_pattern_risk,
                AVG(weekly_visual_health_score) as overall_visual_health_score,
                -- Temporal insights
                AVG(weekly_visual_ads - COALESCE(prev_week_ads, weekly_visual_ads)) as avg_weekly_volume_change,
                AVG(avg_luxury_position - COALESCE(prev_luxury_position, avg_luxury_position)) as avg_luxury_shift,
                AVG(avg_boldness - COALESCE(prev_boldness, avg_boldness)) as avg_boldness_shift,
                AVG(avg_brand_consistency - COALESCE(prev_brand_consistency, avg_brand_consistency)) as avg_consistency_shift,
                AVG(avg_pattern_risk - COALESCE(prev_pattern_risk, avg_pattern_risk)) as avg_fatigue_trend,
                AVG(weekly_volume_rank) as avg_volume_rank,
                AVG(weekly_luxury_rank) as avg_luxury_rank,
                AVG(weekly_boldness_rank) as avg_boldness_rank,
                -- Visual strategy evolution trends
                CASE
                  WHEN AVG(avg_luxury_position - COALESCE(prev_luxury_position, avg_luxury_position)) > 0.05 THEN 'MOVING_UPMARKET'
                  WHEN AVG(avg_luxury_position - COALESCE(prev_luxury_position, avg_luxury_position)) < -0.05 THEN 'MOVING_ACCESSIBLE'
                  ELSE 'STABLE_POSITIONING'
                END as luxury_positioning_trend,
                CASE
                  WHEN AVG(avg_boldness - COALESCE(prev_boldness, avg_boldness)) > 0.05 THEN 'INCREASING_BOLDNESS'
                  WHEN AVG(avg_boldness - COALESCE(prev_boldness, avg_boldness)) < -0.05 THEN 'DECREASING_BOLDNESS'
                  ELSE 'STABLE_BOLDNESS'
                END as boldness_trend,
                CASE
                  WHEN AVG(avg_pattern_risk - COALESCE(prev_pattern_risk, avg_pattern_risk)) > 0.1 THEN 'INCREASING_FATIGUE_RISK'
                  WHEN AVG(avg_pattern_risk - COALESCE(prev_pattern_risk, avg_pattern_risk)) < -0.1 THEN 'DECREASING_FATIGUE_RISK'
                  ELSE 'STABLE_FATIGUE'
                END as creative_fatigue_trend,
                -- Positioning quadrant classification
                CASE
                  WHEN AVG(avg_luxury_position) > 0.7 AND AVG(avg_boldness) > 0.7 THEN 'Luxury-Bold'
                  WHEN AVG(avg_luxury_position) > 0.7 AND AVG(avg_boldness) < 0.4 THEN 'Luxury-Subtle'
                  WHEN AVG(avg_luxury_position) < 0.4 AND AVG(avg_boldness) > 0.7 THEN 'Accessible-Bold'
                  ELSE 'Mid-Balanced'
                END as positioning_quadrant,
                -- Competitive positioning
                CASE
                  WHEN AVG(weekly_volume_rank) <= 2 THEN 'VISUAL_LEADER'
                  WHEN AVG(weekly_volume_rank) <= 4 THEN 'STRONG_VISUAL_PLAYER'
                  ELSE 'VISUAL_CHALLENGER'
                END as competitive_position
              FROM temporal_analysis
              GROUP BY brand
            )
            SELECT
              brand,
              weeks_active,
              total_visual_ads,
              ROUND(overall_visual_alignment, 3) as visual_alignment_score,
              ROUND(overall_brand_consistency, 3) as brand_consistency_score,
              ROUND(overall_luxury_position, 3) as luxury_positioning,
              ROUND(overall_boldness, 3) as boldness_score,
              ROUND(overall_differentiation, 3) as differentiation_level,
              ROUND(overall_pattern_risk, 3) as fatigue_risk,
              ROUND(overall_visual_health_score, 3) as overall_visual_health,
              ROUND(avg_weekly_volume_change, 1) as avg_weekly_volume_change,
              ROUND(avg_luxury_shift, 3) as avg_luxury_shift,
              ROUND(avg_boldness_shift, 3) as avg_boldness_shift,
              ROUND(avg_consistency_shift, 3) as avg_consistency_shift,
              ROUND(avg_fatigue_trend, 3) as avg_fatigue_trend,
              luxury_positioning_trend,
              boldness_trend,
              creative_fatigue_trend,
              positioning_quadrant,
              competitive_position,
              ROUND(avg_volume_rank, 1) as avg_volume_rank,
              ROUND(avg_luxury_rank, 1) as avg_luxury_rank,
              ROUND(avg_boldness_rank, 1) as avg_boldness_rank
            FROM visual_summary
            ORDER BY total_visual_ads DESC
            