-- Strategic Inflection Detection Dashboard
-- Generated by Systematic L1→L4 Intelligence Framework
-- Run ID: warby_parker_20250921_192950


        -- Strategic Inflection Detection Dashboard (Phase 3)
        -- Identifies when competitive dynamics shifted significantly

        WITH weekly_metrics AS (
          SELECT
            brand,
            DATE_TRUNC(DATE(start_timestamp), WEEK(MONDAY)) as week_start,

            -- Core strategic metrics
            COUNT(*) as weekly_ads,
            AVG(LENGTH(COALESCE(creative_text, ''))) as avg_creative_length,
            COUNT(DISTINCT media_type) as media_diversity,
            AVG(ARRAY_LENGTH(platforms_array)) as avg_platform_reach,
            SUM(CASE WHEN media_type = 'VIDEO' THEN 1 ELSE 0 END) / COUNT(*) as video_ratio,
            AVG(duration_quality_weight) as avg_quality,

            -- Text sophistication metrics
            AVG(CASE WHEN creative_text LIKE '%limited%' OR creative_text LIKE '%exclusive%'
                     OR creative_text LIKE '%sale%' THEN 1 ELSE 0 END) as urgency_ratio,
            AVG(CASE WHEN creative_text LIKE '%free%' OR creative_text LIKE '%discount%'
                     OR creative_text LIKE '%off%' THEN 1 ELSE 0 END) as promo_ratio

          FROM `bigquery-ai-kaggle-469620.ads_demo.ads_with_dates`
          WHERE creative_text IS NOT NULL
            AND start_timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 20 WEEK)
          GROUP BY brand, week_start
        ),

        inflection_detection AS (
          SELECT
            brand,
            week_start,
            weekly_ads,
            avg_creative_length,
            media_diversity,
            avg_platform_reach,
            video_ratio,
            avg_quality,
            urgency_ratio,
            promo_ratio,

            -- Calculate rolling averages for stability baseline
            AVG(weekly_ads) OVER (
              PARTITION BY brand
              ORDER BY week_start
              ROWS BETWEEN 4 PRECEDING AND 1 PRECEDING
            ) as rolling_avg_ads_4w,

            STDDEV(weekly_ads) OVER (
              PARTITION BY brand
              ORDER BY week_start
              ROWS BETWEEN 4 PRECEDING AND 1 PRECEDING
            ) as rolling_stddev_ads_4w,

            -- Media strategy baseline
            AVG(video_ratio) OVER (
              PARTITION BY brand
              ORDER BY week_start
              ROWS BETWEEN 4 PRECEDING AND 1 PRECEDING
            ) as rolling_avg_video_ratio_4w,

            -- Platform strategy baseline
            AVG(avg_platform_reach) OVER (
              PARTITION BY brand
              ORDER BY week_start
              ROWS BETWEEN 4 PRECEDING AND 1 PRECEDING
            ) as rolling_avg_platform_4w,

            -- Creative strategy baseline
            AVG(avg_creative_length) OVER (
              PARTITION BY brand
              ORDER BY week_start
              ROWS BETWEEN 4 PRECEDING AND 1 PRECEDING
            ) as rolling_avg_creative_length_4w

          FROM weekly_metrics
        ),

        anomaly_detection AS (
          SELECT
            *,

            -- Volume anomaly detection (2 standard deviations)
            CASE
              WHEN ABS(weekly_ads - COALESCE(rolling_avg_ads_4w, weekly_ads)) >
                   2 * COALESCE(rolling_stddev_ads_4w, 0.001) THEN 1
              ELSE 0
            END as volume_anomaly,

            -- Media strategy shift detection (>30% change)
            CASE
              WHEN ABS(video_ratio - COALESCE(rolling_avg_video_ratio_4w, video_ratio)) > 0.3 THEN 1
              ELSE 0
            END as media_strategy_shift,

            -- Platform expansion detection (>1.5 platform change)
            CASE
              WHEN ABS(avg_platform_reach - COALESCE(rolling_avg_platform_4w, avg_platform_reach)) > 1.5 THEN 1
              ELSE 0
            END as platform_strategy_shift,

            -- Creative evolution detection (>50 char average change)
            CASE
              WHEN ABS(avg_creative_length - COALESCE(rolling_avg_creative_length_4w, avg_creative_length)) > 50 THEN 1
              ELSE 0
            END as creative_strategy_shift,

            -- Calculate Z-scores for magnitude
            SAFE_DIVIDE(
              weekly_ads - COALESCE(rolling_avg_ads_4w, weekly_ads),
              COALESCE(rolling_stddev_ads_4w, 1)
            ) as volume_z_score

          FROM inflection_detection
        ),

        competitive_responses AS (
          SELECT
            a.brand,
            a.week_start,
            a.weekly_ads,
            a.volume_anomaly,
            a.media_strategy_shift,
            a.platform_strategy_shift,
            a.creative_strategy_shift,
            a.volume_z_score,

            -- Check if competitors had inflections in the same or following week
            SUM(CASE
              WHEN b.brand != a.brand AND b.volume_anomaly = 1
                   AND b.week_start BETWEEN a.week_start AND DATE_ADD(a.week_start, INTERVAL 2 WEEK)
              THEN 1 ELSE 0
            END) as competitive_response_count,

            -- Identify market-wide shifts
            SUM(CASE
              WHEN b.week_start = a.week_start AND (
                b.volume_anomaly = 1 OR
                b.media_strategy_shift = 1 OR
                b.platform_strategy_shift = 1
              ) THEN 1 ELSE 0
            END) as market_shift_breadth

          FROM anomaly_detection a
          CROSS JOIN anomaly_detection b
          GROUP BY 1,2,3,4,5,6,7,8
        ),

        inflection_summary AS (
          SELECT
            brand,
            week_start,
            weekly_ads,
            ROUND(volume_z_score, 2) as volume_z_score,

            -- Strategic shift indicators
            volume_anomaly,
            media_strategy_shift,
            platform_strategy_shift,
            creative_strategy_shift,

            -- Total strategic changes this week
            (volume_anomaly + media_strategy_shift + platform_strategy_shift + creative_strategy_shift) as total_shifts,

            -- Competitive dynamics
            competitive_response_count,
            market_shift_breadth,

            -- Classify inflection type
            CASE
              WHEN (volume_anomaly + media_strategy_shift + platform_strategy_shift + creative_strategy_shift) >= 3
                THEN 'MAJOR_STRATEGIC_PIVOT'
              WHEN (volume_anomaly + media_strategy_shift + platform_strategy_shift + creative_strategy_shift) >= 2
                THEN 'SIGNIFICANT_ADJUSTMENT'
              WHEN volume_anomaly = 1 AND volume_z_score > 3
                THEN 'VOLUME_SURGE'
              WHEN volume_anomaly = 1 AND volume_z_score < -3
                THEN 'VOLUME_COLLAPSE'
              WHEN media_strategy_shift = 1
                THEN 'MEDIA_STRATEGY_CHANGE'
              WHEN platform_strategy_shift = 1
                THEN 'PLATFORM_EXPANSION'
              WHEN creative_strategy_shift = 1
                THEN 'CREATIVE_EVOLUTION'
              ELSE 'STABLE_STRATEGY'
            END as inflection_type,

            -- Competitive response pattern
            CASE
              WHEN competitive_response_count >= 3 THEN 'TRIGGERED_MARKET_RESPONSE'
              WHEN competitive_response_count >= 1 THEN 'PROMPTED_COMPETITOR_ACTION'
              WHEN market_shift_breadth >= 4 THEN 'PART_OF_MARKET_SHIFT'
              WHEN market_shift_breadth >= 2 THEN 'ALIGNED_WITH_TREND'
              ELSE 'INDEPENDENT_MOVE'
            END as competitive_context,

            -- Strategic importance score
            ROUND(
              ABS(COALESCE(volume_z_score, 0)) * 0.3 +
              (volume_anomaly + media_strategy_shift + platform_strategy_shift + creative_strategy_shift) * 2 +
              LEAST(competitive_response_count, 3) * 0.5 +
              LEAST(market_shift_breadth, 5) * 0.2
            , 2) as inflection_importance_score

          FROM competitive_responses
        )

        SELECT
          brand,
          week_start,
          weekly_ads,
          volume_z_score,
          inflection_type,
          competitive_context,
          inflection_importance_score,
          total_shifts,
          competitive_response_count,
          market_shift_breadth,

          -- Strategic shift details
          CASE WHEN volume_anomaly = 1 THEN 'VOLUME' ELSE NULL END as volume_shift,
          CASE WHEN media_strategy_shift = 1 THEN 'MEDIA' ELSE NULL END as media_shift,
          CASE WHEN platform_strategy_shift = 1 THEN 'PLATFORM' ELSE NULL END as platform_shift,
          CASE WHEN creative_strategy_shift = 1 THEN 'CREATIVE' ELSE NULL END as creative_shift

        FROM inflection_summary
        WHERE week_start >= DATE_SUB(CURRENT_DATE(), INTERVAL 16 WEEK)
          AND inflection_type != 'STABLE_STRATEGY'  -- Only show actual inflections
        ORDER BY inflection_importance_score DESC, week_start DESC
        