-- Creative Intelligence Analysis Dashboard
-- Generated by Systematic L1→L4 Intelligence Framework
-- Run ID: warby_parker_20250917_205448


            -- Creative Intelligence Dashboard
            WITH creative_metrics AS (
              SELECT 
                brand,
                COUNT(*) as total_ads,
                AVG(LENGTH(COALESCE(creative_text, ''))) as avg_creative_length,
                COUNT(DISTINCT REGEXP_EXTRACT(creative_text, r'\b(\w+)\b')) as unique_words,
                SUM(CASE WHEN creative_text LIKE '%!%' THEN 1 ELSE 0 END) as exclamation_ads,
                AVG(CASE WHEN LENGTH(creative_text) > 100 THEN 1.0 ELSE 0.0 END) as long_form_rate,
                -- P2 Enhancement metrics
                AVG(CASE 
                  WHEN LENGTH(COALESCE(creative_text, '')) > 150 THEN 3
                  WHEN LENGTH(COALESCE(creative_text, '')) > 75 THEN 2
                  ELSE 1
                END) as text_length_score,
                AVG(
                  (LENGTH(UPPER(COALESCE(creative_text, ''))) - LENGTH(REPLACE(UPPER(COALESCE(creative_text, '')), brand, ''))) / 
                  GREATEST(LENGTH(brand), 1)
                ) as brand_mention_density
              FROM `bigquery-ai-kaggle-469620.ads_demo.ads_with_dates`
              WHERE creative_text IS NOT NULL
              GROUP BY brand
            )
            SELECT 
              brand,
              total_ads,
              ROUND(avg_creative_length, 1) as avg_creative_length,
              unique_words,
              exclamation_ads,
              ROUND(long_form_rate * 100, 1) as long_form_pct,
              ROUND(text_length_score, 2) as text_optimization_score,
              ROUND(brand_mention_density, 3) as brand_mention_density
            FROM creative_metrics
            ORDER BY total_ads DESC
            