-- Creative Intelligence Analysis Dashboard
-- Generated by Systematic L1→L4 Intelligence Framework
-- Run ID: warby_parker_20250921_000102


            -- Creative Intelligence Dashboard with Temporal Analysis (Phase 1)
            WITH weekly_creative_metrics AS (
              SELECT
                brand,
                DATE_TRUNC(DATE(start_timestamp), WEEK(MONDAY)) as week_start,
                COUNT(*) as weekly_ads,
                AVG(LENGTH(COALESCE(creative_text, ''))) as avg_creative_length,
                COUNT(DISTINCT REGEXP_EXTRACT(creative_text, r'\b(\w+)\b')) as unique_words,
                SUM(CASE WHEN creative_text LIKE '%!%' THEN 1 ELSE 0 END) as exclamation_ads,
                AVG(CASE WHEN LENGTH(creative_text) > 100 THEN 1.0 ELSE 0.0 END) as long_form_rate,
                AVG(CASE
                  WHEN LENGTH(COALESCE(creative_text, '')) > 150 THEN 3
                  WHEN LENGTH(COALESCE(creative_text, '')) > 75 THEN 2
                  ELSE 1
                END) as text_length_score,
                AVG(
                  (LENGTH(UPPER(COALESCE(creative_text, ''))) - LENGTH(REPLACE(UPPER(COALESCE(creative_text, '')), brand, ''))) /
                  GREATEST(LENGTH(brand), 1)
                ) as brand_mention_density
              FROM `bigquery-ai-kaggle-469620.ads_demo.ads_with_dates`
              WHERE creative_text IS NOT NULL
                AND start_timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 12 WEEK)
              GROUP BY brand, week_start
            ),
            temporal_analysis AS (
              SELECT
                brand,
                week_start,
                weekly_ads,
                avg_creative_length,
                text_length_score,
                brand_mention_density,
                -- Week-over-week changes
                LAG(weekly_ads) OVER (PARTITION BY brand ORDER BY week_start) as prev_week_ads,
                LAG(avg_creative_length) OVER (PARTITION BY brand ORDER BY week_start) as prev_week_length,
                LAG(text_length_score) OVER (PARTITION BY brand ORDER BY week_start) as prev_week_text_score,
                -- Competitive ranking
                RANK() OVER (PARTITION BY week_start ORDER BY weekly_ads DESC) as weekly_volume_rank,
                RANK() OVER (PARTITION BY week_start ORDER BY avg_creative_length DESC) as weekly_length_rank,
                LAG(RANK() OVER (PARTITION BY week_start ORDER BY weekly_ads DESC)) OVER (PARTITION BY brand ORDER BY week_start) as prev_volume_rank
              FROM weekly_creative_metrics
            ),
            creative_summary AS (
              SELECT
                brand,
                COUNT(DISTINCT week_start) as weeks_active,
                SUM(weekly_ads) as total_ads,
                AVG(avg_creative_length) as avg_creative_length,
                AVG(text_length_score) as avg_text_score,
                AVG(brand_mention_density) as avg_brand_density,
                -- Temporal insights
                AVG(weekly_ads - COALESCE(prev_week_ads, weekly_ads)) as avg_weekly_volume_change,
                AVG(avg_creative_length - COALESCE(prev_week_length, avg_creative_length)) as avg_weekly_length_change,
                AVG(weekly_volume_rank) as avg_volume_rank,
                MIN(weekly_volume_rank) as best_volume_rank,
                MAX(weekly_volume_rank) as worst_volume_rank,
                -- Trend indicators
                CASE
                  WHEN AVG(weekly_ads - COALESCE(prev_week_ads, weekly_ads)) > 2 THEN 'INCREASING_VOLUME'
                  WHEN AVG(weekly_ads - COALESCE(prev_week_ads, weekly_ads)) < -2 THEN 'DECREASING_VOLUME'
                  ELSE 'STABLE_VOLUME'
                END as volume_trend,
                CASE
                  WHEN AVG(avg_creative_length - COALESCE(prev_week_length, avg_creative_length)) > 10 THEN 'LENGTHENING_CONTENT'
                  WHEN AVG(avg_creative_length - COALESCE(prev_week_length, avg_creative_length)) < -10 THEN 'SHORTENING_CONTENT'
                  ELSE 'STABLE_LENGTH'
                END as content_trend
              FROM temporal_analysis
              GROUP BY brand
            )
            SELECT
              brand,
              weeks_active,
              total_ads,
              ROUND(avg_creative_length, 1) as avg_creative_length,
              ROUND(avg_text_score, 2) as text_optimization_score,
              ROUND(avg_brand_density, 3) as brand_mention_density,
              -- Temporal intelligence
              ROUND(avg_weekly_volume_change, 1) as avg_weekly_volume_change,
              ROUND(avg_weekly_length_change, 1) as avg_weekly_length_change,
              ROUND(avg_volume_rank, 1) as avg_competitive_rank,
              volume_trend,
              content_trend,
              -- Competitive positioning
              CASE
                WHEN avg_volume_rank <= 2 THEN 'MARKET_LEADER'
                WHEN avg_volume_rank <= 4 THEN 'STRONG_PLAYER'
                ELSE 'CHALLENGER'
              END as competitive_position,
              -- Movement indicator
              CASE
                WHEN best_volume_rank < worst_volume_rank THEN 'IMPROVING_POSITION'
                WHEN best_volume_rank > worst_volume_rank THEN 'DECLINING_POSITION'
                ELSE 'STABLE_POSITION'
              END as competitive_movement
            FROM creative_summary
            ORDER BY total_ads DESC
            