-- Channel Intelligence Analysis Dashboard
-- Generated by Systematic L1→L4 Intelligence Framework
-- Run ID: warby_parker_20250918_004958


            -- Channel Intelligence Dashboard
            WITH channel_metrics AS (
              SELECT
                brand,
                publisher_platforms,
                COUNT(*) as ad_count,
                COUNT(DISTINCT ad_archive_id) as unique_campaigns,
                AVG(CASE WHEN publisher_platforms LIKE '%,%' THEN 1.0 ELSE 0.0 END) as cross_platform_rate,
                -- P2 Enhancement metrics
                AVG(CASE
                  WHEN REGEXP_CONTAINS(publisher_platforms, 'Facebook') AND
                       REGEXP_CONTAINS(publisher_platforms, 'Instagram') AND
                       REGEXP_CONTAINS(publisher_platforms, 'Messenger') THEN 3
                  WHEN REGEXP_CONTAINS(publisher_platforms, 'Facebook') AND
                       REGEXP_CONTAINS(publisher_platforms, 'Instagram') THEN 2
                  WHEN publisher_platforms LIKE '%,%' THEN 1
                  ELSE 0
                END) as platform_diversification_score
              FROM `bigquery-ai-kaggle-469620.ads_demo.ads_with_dates`
              GROUP BY brand, publisher_platforms
            )
            SELECT
              brand,
              publisher_platforms,
              ad_count,
              unique_campaigns,
              ROUND(cross_platform_rate * 100, 1) as cross_platform_pct,
              ROUND(platform_diversification_score, 1) as diversification_score
            FROM channel_metrics
            ORDER BY ad_count DESC
            